/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zxd_showyuv_NativeMethods */

#ifndef _Included_com_zxd_showyuv_NativeMethods
#define _Included_com_zxd_showyuv_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zxd_showyuv_NativeMethods
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zxd_showyuv_NativeMethods_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zxd_showyuv_NativeMethods
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zxd_showyuv_NativeMethods_step
  (JNIEnv *, jclass);

/*
 * Class:     com_zxd_showyuv_NativeMethods
 * Method:    decodeOneFrame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zxd_showyuv_NativeMethods_decodeOneFrame
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
