/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zxd_showyuv_NativeMethods */

#ifndef _Included_com_zxd_showyuv_NativeMethods
#define _Included_com_zxd_showyuv_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zxd_showyuv_NativeMethods
 * Method:    onNativeDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zxd_showyuv_NativeMethods_onNativeDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_zxd_showyuv_NativeMethods
 * Method:    onNativeSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zxd_showyuv_NativeMethods_onNativeSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zxd_showyuv_NativeMethods
 * Method:    onNativeSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zxd_showyuv_NativeMethods_onNativeSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_zxd_showyuv_NativeMethods
 * Method:    onNativeSetFilePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zxd_showyuv_NativeMethods_onNativeSetFilePath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
